// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: monikers/proto/monikers.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Monikers_NewGame_FullMethodName = "/monikers.Monikers/NewGame"
)

// MonikersClient is the client API for Monikers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonikersClient interface {
	NewGame(ctx context.Context, in *NewGameRequest, opts ...grpc.CallOption) (*NewGameResponse, error)
}

type monikersClient struct {
	cc grpc.ClientConnInterface
}

func NewMonikersClient(cc grpc.ClientConnInterface) MonikersClient {
	return &monikersClient{cc}
}

func (c *monikersClient) NewGame(ctx context.Context, in *NewGameRequest, opts ...grpc.CallOption) (*NewGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewGameResponse)
	err := c.cc.Invoke(ctx, Monikers_NewGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonikersServer is the server API for Monikers service.
// All implementations must embed UnimplementedMonikersServer
// for forward compatibility.
type MonikersServer interface {
	NewGame(context.Context, *NewGameRequest) (*NewGameResponse, error)
	mustEmbedUnimplementedMonikersServer()
}

// UnimplementedMonikersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonikersServer struct{}

func (UnimplementedMonikersServer) NewGame(context.Context, *NewGameRequest) (*NewGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewGame not implemented")
}
func (UnimplementedMonikersServer) mustEmbedUnimplementedMonikersServer() {}
func (UnimplementedMonikersServer) testEmbeddedByValue()                  {}

// UnsafeMonikersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonikersServer will
// result in compilation errors.
type UnsafeMonikersServer interface {
	mustEmbedUnimplementedMonikersServer()
}

func RegisterMonikersServer(s grpc.ServiceRegistrar, srv MonikersServer) {
	// If the following call pancis, it indicates UnimplementedMonikersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Monikers_ServiceDesc, srv)
}

func _Monikers_NewGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonikersServer).NewGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Monikers_NewGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonikersServer).NewGame(ctx, req.(*NewGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Monikers_ServiceDesc is the grpc.ServiceDesc for Monikers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Monikers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monikers.Monikers",
	HandlerType: (*MonikersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewGame",
			Handler:    _Monikers_NewGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monikers/proto/monikers.proto",
}
